export const AUDIT_ACTIONS = {
  // Auth actions
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',

  // User actions
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',

  // Campaign actions
  CAMPAIGN_CREATED: 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED: 'CAMPAIGN_UPDATED',
  CAMPAIGN_DELETED: 'CAMPAIGN_DELETED',
  CAMPAIGN_USER_ASSIGNED: 'CAMPAIGN_USER_ASSIGNED',
  CAMPAIGN_USER_REMOVED: 'CAMPAIGN_USER_REMOVED',

  // Security Event actions
  SECURITY_EVENT_CREATED: 'SECURITY_EVENT_CREATED',
  SECURITY_EVENT_UPDATED: 'SECURITY_EVENT_UPDATED',
};

export const AUDIT_RESOURCE_TYPES = {
  AUTH: 'AUTH',
  USER: 'USER',
  CAMPAIGN: 'CAMPAIGN',
  SECURITY_EVENT: 'SECURITY_EVENT',
};
